### ISSUE TITLE
.vimrc on linux mint/ubuntu

### ISSUE THREAD

**Issue by Modicrumb** [markstory/vim-files#1]
This might be different just on my linux mint system but...
to run the install script I needed to change a line of the makefile to be like this:

  cd bundle/command-t/ruby/command-t

Also I needed ruby dev tools to finish installing it. Cool stuff though. I just wanted to be able to copy your stuff without looking into all those plug ins individually and whatever. I suppose it works. Great!

**Comment by markstory** [comment]
I honestly never use mint, but if you have a change that would make the install script better a pull request would be awesome.

**Comment by Modicrumb** [comment]
pull request created!
