### ISSUE TITLE
Colors on Mac Os X

### ISSUE THREAD

**Issue by midorikocak** [markstory/vim-files#3]
Actually the colors are weird. Is it my computer making problems with colors?

iterm:
![iterm](https://cloud.githubusercontent.com/assets/545472/8065147/d9d008aa-0edf-11e5-8f73-7570239aefd0.png)

terminal
![terminal](https://cloud.githubusercontent.com/assets/545472/8065148/d9d0ae4a-0edf-11e5-8ea9-cb285a2ec634.png)

**Comment by markstory** [comment]
You need to not use Terminal.app. It doesn't support 256 colours out of the box. I suggest you try iTerm2 instead.

**Comment by midorikocak** [comment]
Actually the first one is iterm2

![screen shot 2015-06-14 at 00 39 16](https://cloud.githubusercontent.com/assets/545472/8146245/f1b8265e-122d-11e5-9b53-1d4fe985478c.png)

**Comment by ryansnowden** [comment]
Sometimes, depending on whats happening in peoples terminals, you gotta put something like export TERM='xterm-256color'; in your .bashrc/.bash_profile

**Comment by markstory** [comment]
It might be the default color schemes as well then. I use [solarized light](http://ethanschoonover.com/solarized) for my terminal defaults which might be part of the issue. If you don't want to change your terminal scheme, you can choose a new `colorscheme` in the `vimrc` file.
